baseurl = "http://ernstkui.github.io/vanhoosedotwork/"
languageCode = "en-us"
title = "vanhoosedotwork"
theme = "hugo-creative-theme"
canonifyUrls = true

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more informtion take a look at the README.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Katherine VanHoose"
	description = "Freelance editor, designer and consultant for topics related to the built environment."

	# Navigation
	[params.navigation]
		brand = "VanHooseDotWork"

		[params.navigation.links]
			about     = "About"
			portfolio = "My work"
			services  = "Your work"
			contact   = "Let's work together."


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "VANHOOSE DOT WORK"
		subtitle   = "Bringing change to the built environment"
		buttonText = "Find out more"


	# About section
	[params.about]
		headline    = "VanHooseDotWork"
		profilePicture = "IMG_4585.jpg"
		description = "Hi! My name is Katherine and I am an American currently based in Utrecht, the Netherlands. I am a designer and researcher with a passion for creating and seeing-through positive change in cities. At VanHooseDotWork we help create impact through a combinatory approach: design thinking, research and strong communication. Thinking outside of the box, finding out more and engaging others. Every problem has a solution: it's about knowing who to engage and which tools to use. Each project is approached with a fresh perspective and there's no copying and pasting. Strong ommunication skills, graphic design, and the ability to develop concepts into creative solutions brings us further in each project that we do, no matter how small or big. We have found this approach to be valuable for a variety of projects and for a number of clients. For an idea of what we can do for you, please see [the services](#services) below or check out [my work](#portfolio) for an example of the topics that keep us busy and excited. Let's get in touch!"

		buttonText  = "Download CV"
		buttonUrl = 'https://www.dropbox.com/s/nvgi3qt10d0bi6l/VanHoose_CV_ENG_Recent.pdf?raw=1'

	# Service section
	[params.services]
		headline = "Services"

        [[params.services.list]]
            icon = "icon-editingicon"
            title = "Communication"
            tags = "Editing, translating and consulting"
            description = "Your project can be strengthened by my expertise in editing and translating (Dutch to English). I can also bring my verbal skills to organize workshops or day events. Projects in the built environment revolve around communication, whether it be written or verbal. Strongly expressing your ideas and connecting with others is a crucial factor. Let’s begin our collaboration with an open dialogue about your work and goals."

		[[params.services.list]]
            icon = "icon-consultingicon"
            title = "Research"
            tags = "Fieldwork, deskwork and analysis"
            description = "I bring my observation and analytical skills to map your problem, going deep into your topic or issue and giving attention to underlying aspects. Asking the right questions and critically analyzing the results: that is what my approach is all about. Every project is unique and requires a specific approach for establishing solutions. Let's get in touch to find out the best way to research the central issue of your project."

        [[params.services.list]]
			icon = "icon-designingicon"
			title = "Design"
			tags = "Consulting, creating and producing"
			description = "I can translate your ideas and complex qualitative and quantitative data and concepts into clear and compelling print and digital materials. A strong visual appearance is the better half of already strong content. Whether it be communicative diagrams, layout design or marketing materials, let’s think together to find the best way to visually express your work when words are at a minimum."

    # Portfolio modals
	[params.portfolio.modal]
        collaborator = "Collaborators"
        date = "Date"
        category = "Category"
        buttonText = "Close"

	# Contact section
	[params.contact]
		headline = "Let's work together."
		description = "VanHooseDotWork is always open to new collaborations and projects. If you would like to get a quote, learn a bit more about the services I offer, or grab a cup of coffee, feel free to contact me."
		phone = "+31 (0)6 38 32 68 78"
		email = "katherine@vanhoose.work"
		twitter = "katevanhoose"
		kvknumber = "64 86 28 44"
		pictures = "Let's Talk About the Polders Again, Merten Nefs; (re) Making City, Magnus Lundqvist"

