baseurl = "http://ernstkui.github.io/vanhoosedotwork/"
languageCode = "en-us"
title = "vanhoosedotwork"
theme = "hugo-creative-theme"
canonifyUrls = true

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more informtion take a look at the README.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Katherine VanHoose"
	description = "Editor Translator Designer Sociologist with a passion for cities"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "VanHooseDotWork"

		[params.navigation.links]
			about     = "+ My Work"
			services  = "Your Work"
			# portfolio = "Portfolio"
			contact   = "Let's work together"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "VANHOOSE DOT WORK"
		subtitle   = "Researcher with a wide range of experiences in the built environment"
		buttonText = "Find out more"


	# About section
	[params.about]
		headline    = "My Work"
		description = "Hi! My name is Katherine VanHoose and I am a designer and researcher. I see value in combining the structured and analytical methods of social science with the creative power of design to make a positive impact on issues related to cities and the built environment. A combination of content and process-based work challenges me the most, while working with others gives me energy and sparks my creativity. I have developed a variety of services aimed at non-profits, small businesses, architectural firms, academic institutions and individual authors busy with topics related to the built environment. My interdisciplinary background This wide discipline covers a range of themes, including architecture and design, real estate and housing, urban and spatial planning, as well as urban sociology and geography. I value communication and transparency. Throughout you have full discretion and are able to approach me at anytime for updates, comments or questions. With training as an architect and social science researcher, years of experience working in a number of environments with others interested in urban issues have given me a wide skillset. I offer a tangible, affordable and result-focused approach to editing and design services. I am currently based in in Utrecht, the Netherlands and serve both local clients as well as others situated throughout Europe."
		buttonText  = "Let’s get in touch!"


	# Service section
	[params.services]
		headline = "Services"

        [[params.services.list]]
            icon = "fa-check-square-o"
            title = "Editing"
            description = "Quality English editing with a quick turn around. 30 - 35 euros/hour."

        [[params.services.list]]
			icon = "fa-file-text"
			title = "Formatting"
			description = "Meeting citation and formatting requirements for journals. Specifically for academic and scientific authors who are preparing to submit their article to a journal."

		[[params.services.list]]
            icon = "fa-language"
            title = "Translating"
            description = "Translating services are available for texts written in Dutch that need to be translated into English. I specialize in topics directly related to the built environment. 0,06 euro cents/word."

        [[params.services.list]]
            icon = "fa-picture-o"
            title = "Designing"
            description = "Good design is a good investment. The layout service turn your bland word document into a well-designed publication based on your specifications and wishes. 50 euros per figure, flat rate."


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "More of my work"

		[params.aside.button]
			text = "Get my resume and portfolio"
			link = "//github.com/digitalcraftsman/hugo-creative-theme"

	# Contact section
	[params.contact]
		headline = "Let's work together"
		description = "If you would like to get a quote or learn a bit more about the services I offer, please feel free to contact me!"
		phone = "+31 (0)6 38 32 68 78"
		email = "katherine@vanhoose.work"
