baseurl = "http://ernstkui.github.io/vanhoosedotwork/"
languageCode = "en-us"
title = "vanhoosedotwork"
theme = "hugo-creative-theme"
canonifyUrls = true

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more informtion take a look at the README.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Katherine VanHoose"
	description = "Editor Translator Designer Sociologist with a passion for cities"

	# Navigation
	[params.navigation]
		brand = "VanHooseDotWork"

		[params.navigation.links]
			about     = "My work"
			services  = "Your work"
			# portfolio = "Portfolio"
			contact   = "Let's work together"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "VANHOOSE DOT WORK"
		subtitle   = "Freelance designer, researcher and thinker"
		buttonText = "Find out more"


	# About section
	[params.about]
		headline    = "VanHooseDotWork"
		profilePicture = "IMG_4585.jpg"
		description = "Hi! My name is Katherine and I am an American currently based in Utrecht, the Netherlands. I am a designer and researcher with a passion for cities. I believe that when the structured and analytical methods of social science are combined with the creative power of design, powerful solutions to seemingly complex issues in the built environment can be reached. This approach combines communication, graphic and analytical skills, which I have developed over the past six years in both professional and academic contexts. Through these experiences, I have found this approach to be valuable on a number of scales and for a variety of projects. I creatively turn ideas into concrete results for clients with social issues in the built environment. For an idea of what this approach can mean for you, please see the services section below. Let's get in touch!"

		buttonText  = "Download CV"
		buttonUrl = 'https://www.dropbox.com/s/svune2r4y24jr8f/VanHoose_CV.pdf/?raw=1'

	# Service section
	[params.services]
		headline = "Services"

        [[params.services.list]]
            icon = "fa-file-text-o"
            title = "Written"
            description = "English Editing and Translating from Dutch to English. As a researcher I understand the importance of strongly communicating ideas. I have edited and translated a variety of written publications concerning themes related to the built environment on behalf of academic authors, non-profits, small businesses and individuals. A fast and high-quality edit of your publication, project proposal, article or text."

		[[params.services.list]]
            icon = "fa-lightbulb-o"
            title = "Analytical"
            description = "Research and consultancy. I have collaborated on a number of projects that involve creatively approaching complex issues or uncovering interesting phenomenon related to the built enironment. My method of work is hands on: researching and defining the problem, organizing and communicating with multiple parties, searching for feasable and reasonable solutions and circulating results. Take a look at my work for an idea of what this approach can mean for you."

        [[params.services.list]]
			icon = "fa-pencil"
			title = "Visual"
			description = "Graphic design. As a trained designer, I understand the importance (and advantage) of presenting material in a visually appealing way. My experience lies in the creation of maps, communcative diagrams and layout design. Let’s think together to find the best way to present your work."

    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

	# Contact section
	[params.contact]
		headline = "Let's work together"
		description = "VanHooseDotWork is always open to new collaborations and projects. If you would like to get a quote or learn a bit more about the services I offer, please feel free to contact me."
		phone = "+31 (0)6 38 32 68 78"
		email = "kavanhoose@gmail.com"
		twitter = "katevanhoose"
		instagram = "kavanhoose"
